wandb_version: 1

exp_name:
  desc: null
  value: ppo
gym_id:
  desc: null
  value: CartPole-v1
learning_rate:
  desc: null
  value: 0.00025
seed:
  desc: null
  value: 1
total_timesteps:
  desc: null
  value: 25000
torch_deterministic:
  desc: null
  value: true
cuda:
  desc: null
  value: true
track:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: ppo-implementation-details
wandb_entity:
  desc: null
  value: null
capture_video:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    code_path: code/Python/Capstone Playground/PPO_Tutorial/ppo.py
    python_version: 3.8.0
    cli_version: 0.16.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1701328375.058797
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.0
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
